version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.19.5
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "devroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/data:/vault/file
      - ./vault/config:/vault/config:ro
    entrypoint: vault server -dev -dev-root-token-id=devroot -dev-listen-address="0.0.0.0:8200"